import { Metadata } from "next"
import "./globals.css";
// import { ErrorWrapper } from "./error-wrapper";
export const metadata:Metadata ={
  title : {
      default:"Next.js toutorial - codevolution",
      template:"%s | codevolution",
  },
  description:"Generated by next.js"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <header style={{
          backgroundColor:"lightblue",
         
          padding:"1rem"
        }}>
          <p>header</p>
        </header>
        {/* <ErrorWrapper> */}
              {children}
        {/* </ErrorWrapper> */}
        <footer style={{
            backgroundColor :"lightblue",
            padding:"1rem",
             
        }}>

            <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}